<?php include __DIR__ . '/header.phtml'; ?>
    <main class="homeMain">
        <div class="homeSearch">
            <h1>Partez au vert avec EcoRide</h1>
            <h2>Le premier site de covoiturage qui s'adapte à vos convictions écologiques</h2>
            <form class="formSearchDestination" method="get">
                <fieldset class="fieldSearchDestination">
                    <p class="iconSearch"><span class="icon-location"></span></p>
                    <input class="textSearch" type="text" name="destination" id="destination" placeholder="Où allons-nous?">
                    <a href="covoiturage.phtml" class="btnSbumit btnSearch" type="submit">Rechercher</a>
                </fieldset>
            </form>
        </div>
        <div class="homeDescription">
            <p>La startup "EcoRide" fraichement crée en France, a pour objectif de réduire l'impact environnemental des déplacements en encourageant le covoiturage. EcoRide prône une approche écologique et souhaite se faire connaître au travers du grand public.</p>

            <p>L’ambition "EcoRide" est de devenir la principale plateforme de covoiturage pour les voyageurs soucieux de l'environnement et ceux qui recherchent une solution économique pour leurs déplacements.</p>
        </div>
    </main>
    <?php include __DIR__ . '/footer.phtml'; ?>