<?php include __DIR__ . '/header.phtml'; ?>
    <main class="covoiturageMain">
        <form class="formSearchDestination" method="get">
            <fieldset class="fieldSearchDestination">
                <label for="destination" class="iconSearch"><span class="icon-location"></span></label>
                <input class="textSearch" type="text" name="destination" id="destination" placeholder="Où allons-nous?">
                <button class="btnSbumit btnSearch" type="submit">Rechercher</button>
            </fieldset>
            <fieldset class="fieldFiltersDestination">
                <div class="filtersDestination">
                    <label for="startLocalisation">Où?</label>
                    <input type="text" id="startLocalisation" name="startLocalisation">
                </div>
                <div class="filtersDestination">
                    <label for="startDate">Quand?</label>
                    <input type="datetime-local" id="startDate" name="startDate">
                </div>
                <div class="filtersDestination">
                    <label for="time">Durée</label>
                    <input type="time" id="time" name="time">
                </div>
                <div class="filtersDestination">
                    <label for="price">Prix</label>
                    <input type="number" id="price" name="price">
                </div>
                <div class="filtersDestination">
                    <label for="marck">Note Minimum</label>
                    <input type="number" id="marck" name="marck" value="0" min="0" max="5">
                </div>
            </fieldset>
        </form>
        
    </main>
    <?php include __DIR__ . '/footer.phtml'; ?>